// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://tjjcrcotnxvkdpxjjync.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqamNyY290bnh2a2RweGpqeW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1MTc0MTAsImV4cCI6MjEwMjA5MzQxMH0.uT8Q-VCd_QUd51zf-_dyKvzkxNDhp7rZ3NL4cTJm1rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});